### ISSUE TITLE
Print warning if `$ref`s are used that are not supported

### ISSUE THREAD

**Issue by Profpatsch** [tamasfe/taplo#120]
taplo currently only resolves `"$ref"` links if they are

* local references
* absolute
* In the *exact* path `#/definitions/…`

We should print a warning if the user tries do do something else, otherwise it just silently does nothing and the UX is not great. Source: stumbled into this myself

Relevant part of the code:

https://github.com/tamasfe/taplo/blob/b98bf91bbdaf9a0f4f8ba42fdf48a132c932dbf0/taplo/src/schema.rs#L425-L431

**Comment by tamasfe** [comment]
This is documented [here](https://taplo.tamasfe.dev/configuration/#limitations-and-unimplemented-features). Although indeed, a warning would be nice.

I think currently it is not only silently fails but actually should crash the LSP since [`verify`](https://github.com/tamasfe/verify) that is used for validations doesn't support `$ref` resolution either.

**Comment by Profpatsch** [comment]
> This is documented [here](https://taplo.tamasfe.dev/configuration/#limitations-and-unimplemented-features). Although indeed, a warning would be nice.

yes, that’s how I figured it out in the end :)
