### ISSUE TITLE
Inconsistent Behavior

### ISSUE THREAD

**Issue by AurevoirXavier** [tamasfe/taplo#139]
```toml
# Enable auto expand with disable auto collapse
## In 0.12.2
ethereum-types  = { version = "0.12.0", default-features = false, features = ["codec", "rlp"] }
## In 0.13.1
### And this is not right
ethereum-types  = { version = "0.12.0", default-features = false, features = [
    "codec",
    "rlp"
] }

# Disable auto expand with disable auto collapse
## In 0.12.2
crates-std    = [
	"codec/std",
	"ethbloom/std",
	"ethereum-types/std",
	"ethereum-types/serialize",
	"fixed-hash/std",
	"impl-codec/std",
	"impl-rlp/std",
	"keccak-hash/std",
	"primitive-types/std",
	"rlp/std",
	"serde",
]
darwinia-std  = [
	"ethash/std",
	"merkle-patricia-trie/std",
]
substrate-std = [
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]

deserialize  = []
with-new-dag = []
## In 0.13.1
### Expanded entries not get align
crates-std = [
	"codec/std",
	"ethbloom/std",
	"ethereum-types/std",
	"ethereum-types/serialize",
	"fixed-hash/std",
	"impl-codec/std",
	"impl-rlp/std",
	"keccak-hash/std",
	"primitive-types/std",
	"rlp/std",
	"serde",
]
darwinia-std = [
	"ethash/std",
	"merkle-patricia-trie/std",
]
substrate-std = [
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
### Empty entries get align
deserialize  = []
with-new-dag = []
```

**Comment by tamasfe** [comment]
Hi, thanks for the report.

If I understand correctly, there are two concerns here:

- Arrays being expanded in the new version, while they weren't in the previous versions. This is due to `columnWidth` being actually more closely respected, reducing `columnWidth` or adding more entries into the inline array would cause the same behaviour in the old version, so this is intentional.
- Items spanning multiple lines are not aligned. Indeed this is the case, because I don't exactly know how they should be aligned, as aligning them doesn't make a lot of sense. I might align the first lines only, so that would mimic the behaviour of the old formatter.

**Comment by AurevoirXavier** [comment]
> Hi, thanks for the report.
> 
> If I understand correctly, there are two concerns here:
> 
>     * Arrays being expanded in the new version, while they weren't in the previous versions. This is due to `columnWidth` being actually more closely respected, reducing `columnWidth` or adding more entries into the inline table would cause the same behaviour in the old version, so this is intentional.
> 
>     * Items spanning multiple lines are not aligned. Indeed this is the case, because I don't exactly know how they should be aligned, e.g. what should happen with comments. I might align the first lines only, so that would mimic the behaviour of the old formatter.

Yes.

And I really need the second one, which made the format much concise and easy to review.

**Comment by tamasfe** [comment]
Sorry, implementing this properly is out of scope for me currently.
