### ISSUE TITLE
Less non standard features in schemas

### ISSUE THREAD

**Issue by HKalbasi** [tamasfe/taplo#166]
So it can be useful for other tools and maybe we can put cargo schemas in https://www.schemastore.org/json/

From What I see, there is two major non standard things:
* link to official documentation, which can be a simple `[more information](link)` somewhere in the doc. (am I missing something?)
* `hidden: true` which I didn't get what is the propose of it
* documentation for enum values. It seems this is the standard way:
```
"oneOf": [
    { "const": "a", "description": "A" },
    { "const": "b", "description": "B" },
    { "const": "c", "description": "C" }
  ]
```

If it won't have negative effect on taplo, I can replace them with standard alternative.

**Comment by tamasfe** [comment]
I'm all for standardization, but unfortunately none of what you propose is possible right now.

> link to official documentation, which can be a simple `[more information](link)` somewhere in the doc. (am I missing something?)

Yes, the extension has a feature where the keys themselves are clickable links, some people find it distracting but I personally like it.

> `hidden: true` which I didn't get what is the propose of it

It hides the item from suggestions.

>  documentation for enum values. It seems this is the standard way:

This is currently not possible because composite schemas are not implemented properly (#57).

**Comment by HKalbasi** [comment]
> This is currently not possible because composite schemas are not implemented properly (#57).

For enums, merging all suggestions is the correct way. So #57 isn't a blocker?

**Comment by tamasfe** [comment]
The implementation is pretty much half-assed, e.g. all the documentation will be merged in every case when you hover over the values iirc.

I'd encourage you to experiment with it though if you have the time, and I'll gladly accept PRs if you find a working solution.

**Comment by ssbarnea** [comment]
@tamasfe I was about to ask why this extension is not already using schemastore for gathering schemas and associations. Do we really diverge from json schemas to an extend that makes impossible to do so?

I had one case where I added a extra property at root level of Ansible JSON schemas in order to expose the file patterns that schema is supposed to match. That is not inside JSON Schema spec but that does not make the document invalid because these schemas do not have `additionalProperties: false`, so adding extra keys is ok-ish, with a very small chance of having to do some changes in a future revision of the spec.

Another question that I have is related to maintenance status of this extension. I seen that only a round of 5 releases was made about 6 months ago without anything since. Is it actively maintained? Do we have a backup maintained that can takeover if you become unavailable? -- Just to clarify that is my attempt to do a risk assessment before deciding if I should promoting this extension as part of [Ansible language extension](https://marketplace.visualstudio.com/items?itemName=redhat.ansible) which also [installs two other extensions](https://github.com/ansible/vscode-ansible/blob/main/package.json#L425-L426).

**Comment by tamasfe** [comment]
> Do we really diverge from json schemas to an extend that makes impossible to do so?

One of the reasons is that the extension uses regex for entire uris for associations while the schemastore used globs for file names the last time I checked, this could be easily worked around though. The other more important reason is that schema implementations are pretty much sub-optimal, both the validation and the completions, the JSON schema spec is only partially supported. So yes, unless the schema is specifically made for taplo, it is not likely to work in most cases. A schema rework is definitely in the plans, but it's a larger undertaking.

> Is it actively maintained?

The correct term would be "passively maintained" if it existed. Right now it kind of works with caveats, and I work on it irregularly whenever I find the time. I'm just about to finish uni and I am currently catching up on projects with the additional free-time I got back, so most likely I will eventually get to this one as well. 

> if I should promoting this extension

Probably not in its current state, I would only recommend it after the schema rework is done and when I'm not the only maintainer anymore.

**Comment by tamasfe** [comment]
With the new schema implementation, more features of the standard draft 4 schemas are supported along with the schema store as well.

The extension field stayed for backwards compatibility, and the features that regular schemas cannot convey (like `links`, and `hidden`), it's entirely opt-in.

I'll consider this issue resolved, standard schemas should just work, if you encounter any problems, please open specific issues for them.
