### ISSUE TITLE
Saving a file gets stuck on the formatter in VSCodium

### ISSUE THREAD

**Issue by 4JX** [tamasfe/taplo#189]
Any modifications made to `Makefile.toml` (used by `cargo-make`, see file [here](https://github.com/4JX/L5P-Keyboard-RGB/blob/main/Makefile.toml)) make the formatter get stuck with the following prompt: https://ibb.co/BtKdZrF.

I do also have Better TOML (installed but disabled, tried uninstalling it as well and it did not make any difference) and Prettier but I don't think those would cause any issues. Formatting is done on save.

After a while, it does throw the following error:
```sh
/home/user/.vscode-oss/extensions/tamasfe.even-better-toml-0.14.2/dist/server.js:81
    throw up;
    ^

RuntimeError: unreachable
    at <anonymous>:wasm-function[3277]:0x38cb10
    at <anonymous>:wasm-function[332]:0x212586
    at <anonymous>:wasm-function[1771]:0x35f6dd
    at <anonymous>:wasm-function[1486]:0x345aff
    at <anonymous>:wasm-function[264]:0x1d9591
    at <anonymous>:wasm-function[102]:0xc751b
    at <anonymous>:wasm-function[3117]:0x38c268
    at <anonymous>:wasm-function[99]:0xbab2f
    at <anonymous>:wasm-function[3120]:0x38c28c
    at <anonymous>:wasm-function[1352]:0x336a30
[Info  - 16:56:35] Connection to server got closed. Server will restart.
[Error - 16:56:35] Request textDocument/completion failed.
Error: Connection got disposed.
	at Object.dispose (/home/user/.vscode-oss/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:5570:27)
	at Object.dispose (/home/user/.vscode-oss/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:11022:35)
	at LanguageClient.handleConnectionClosed (/home/user/.vscode-oss/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:13372:42)
	at LanguageClient.handleConnectionClosed (/home/user/.vscode-oss/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:16276:15)
	at closeHandler (/home/user/.vscode-oss/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:13359:18)
	at CallbackList.invoke (/home/user/.vscode-oss/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:3569:39)
	at Emitter.fire (/home/user/.vscode-oss/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:3631:36)
	at closeHandler (/home/user/.vscode-oss/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:4783:26)
	at CallbackList.invoke (/home/user/.vscode-oss/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:3569:39)
	at Emitter.fire (/home/user/.vscode-oss/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:3631:36)
	at IPCMessageReader.fireClose (/home/user/.vscode-oss/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:3780:27)
	at ChildProcess.<anonymous> (/home/user/.vscode-oss/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:5720:45)
	at ChildProcess.emit (events.js:327:22)
	at maybeClose (internal/child_process.js:1048:16)
	at Socket.<anonymous> (internal/child_process.js:439:11)
	at Socket.emit (events.js:315:20)
```

**Comment by tamasfe** [comment]
Thanks for the report, the image link doesn't point to any images.

> After a while, it does throw the following error:

The error you're getting is a long-standing issue probably due to an unfinished feature, it is annoying but it should be harmless.

I cannot reproduce the issue with the same file, manually formatting it and even enabling autoformat works.

Does manually formatting it cause the same issue, and does it always hang?

**Comment by 4JX** [comment]
> Thanks for the report, the image link doesn't point to any images.

Whoops, fixed that.

> I cannot reproduce the issue with the same file, manually formatting it and even enabling autoformat works.
> 
> Does manually formatting it cause the same issue, and does it always hang?

Yes. It seems I was ruling out one other variable from my testing, I am using [VSCodium](https://github.com/VSCodium/vscodium), not [VSCode](https://github.com/microsoft/vscode) itself. It's weird that it would break when all VSCodium does is take the raw VSCode repo and add a few scripts while building to disable telemetry, but I guess Microsoft could also be packing some extra features into VSCode in its build process.

That being said it would seem like momentarily installing VSCode fixed the issue(?). I'm not sure, really, but it seems to be working now (Or at least formatting code). Don't know how it'll behave in the long run.

**Comment by tamasfe** [comment]
> VSCodium does is take the raw VSCode repo and add a few scripts while building to disable telemetry

I can't think of any specific reason for incompatibility other than different versions with probably breaking extension API changes (?), the same package is pushed to open-vsx so the extensions should be identical as well, the cause can be anything really.

One thing worth checking if you have the time is the dev console (`crtl+shift+I` or `Toggle Developer Tools` under `Help`) to see if it contains anything useful. Otherwise I'd leave this open and I'll hopefully come back to it at some point.

**Comment by 4JX** [comment]
![BehaviourIsDifferent (1)](https://user-images.githubusercontent.com/79868816/142773996-317392f8-54f9-4669-ab7c-83d35aea3999.gif)
Left is VSCodium, right is VSCode. Something is going wrong on the Codium side of things.

**Comment by tamasfe** [comment]
Quite weird, I will have to look deeper into whatever is going on in VSCodium.

**Comment by tamasfe** [comment]
Actually, I might have some idea. The schemas on VSCode currently don't work due to letsencrypt's certificate expiration, that's why you're only getting syntax errors there.

Can you see if disabling schemas helps in VSCodium by disabling them via `"evenBetterToml.schema.enabled": false`? If it's a schema (performance) issue, it's quite unfortunate as I'm planning to rewrite how schemas are handled altogether and it seems to be quite a bit of work.

**Comment by 4JX** [comment]
> Can you see if disabling schemas helps in VSCodium by disabling them via `"evenBetterToml.schema.enabled": false`? If it's a schema (performance) issue, it's quite unfortunate as I'm planning to rewrite how schemas are handled altogether and it seems to be quite a bit of work.

Added it to the workspace config, restarted the app and sure enough it worked. :+1:

**Comment by tamasfe** [comment]
Great, this is basically #136 then judging by the performance issue probably due to a large or complex schema.

Instead of disabling all schemas, you can just set an empty (or any invalid) association for `Makefile.toml`:

```json
"evenBetterToml.schema.associations": {
    "^(.*(/|\\\\)Makefile\\.toml|Makefile\\.toml)$": ""
}
```

You will still have validation and completion for other files (`Cargo.toml` for example), unless they all have this issue.
