### ISSUE TITLE
VS Code: allow other extensions to contribute schemas

### ISSUE THREAD

**Issue by itowlson** [tamasfe/taplo#222]
I'm working on a VS Code extension, and as part of that I'd like to provide schema validation for a particular kind of TOML file.  I'd really like to use Even Better TOML, rather than writing something custom, but I can't see a way for my extension to specify a schema for a document.  The only way I can see is through VS Code configuration settings, and I don't want my extension to mess with the user's config.

As an analogy, the Red Hat YAML extension provides an API by which an extension can register as a schema contributor.  When RH YAML needs a schema for a file, it consults all registered contributors: if one of them offers a schema based on the file path or content, it will use that schema for that file.

Would you be willing to provide a facility like this?  Or would you be open to a pull request if I can figure out how to add it myself?  Thanks!

**Comment by tamasfe** [comment]
Yes, I'm definitely open to this.

I wouldn't recommend creating PRs as the `next` branch pretty much changed everything but is still mostly undocumented.

Figuring out how to iterate through all the other extension contributions would be great help, other than that it shouldn't take a lot of effort to support this feature.

**Comment by itowlson** [comment]
I don't know enough about the Even Better TOML architecture to know how feasible various approaches are, but let me share what I know from the YAML world.

The way the YAML extension handles this is by returning an API object from `activate()`.  Other extensions can then get this object via the VS Code API.  Their object provides a method to register a contributor:

```
export interface ExtensionAPI {
  registerContributor(
    schema: string,
    requestSchema: (resource: string) => string,
    requestSchemaContent: (uri: string) => string,
    label?: string
  ): boolean;
  modifySchemaContent(schemaModifications: SchemaAdditions | SchemaDeletions): Promise<void>;
}
```

https://github.com/redhat-developer/vscode-yaml/blob/main/src/schema-extension-api.ts

An example of using their API: https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/blob/53530469c73a0ac089b1b57094f491d0f91b2a8d/src/yaml-support/yaml-schema.ts#L31

I don't know if you would need the full flexibility of their interface (I'm not sure why they designed it to have so many decoupling points) - more likely you could get away with other extensions just registering a document selector and a schema (or a function from document ID to schema, which would allow the contributor to peek at the TOML body before picking which schema to use).

The big architectural difference compared to configuration, or to iterating over other extensions, is that this means you never assemble a full, static set of schemas (or document->schema mappings).  At any time after your extension activates, a new extension may activate and call the registration API.  So I don't know how well this is going to fit in with your planned architecture!

To be clear, I'm not trying to push you down this specific route.  I'm sharing it because it's the one that I've experienced.  If it's not going to work for you, or doesn't feel right, I'd be very happy to chat about other approaches.

Thanks heaps for the positive response - I hope this was a useful brain dump!

**Comment by tamasfe** [comment]
Thanks for the great writeup!

> I hope this was a useful brain dump!

Yes, it's very much appreciated.

I think your approach is orthogonal to what I had in mind, and I'm sure we can have both.

Currently schema associations work the following way:

They have a *rule* that is one of:

- a regex pattern of a document URI
- a glob pattern of a document URI
- an exact document URI

That maps to an *association*:

- a (remote) schema URL
- some metadata (such as the source of the association itself, title, description, etc.)
- and a priority

The LSP handles all schema fetching, caching and expiration.

Adding or removing associations of this kind is pretty much trivial.

The YAML API seems quite a bit more complex, however it solves the following:

- it notifies the extension if a schema has expired from cache
- the extensions have their own methods of pulling schemas, including handling authentication and non-conventional ways (such as from k8s clusters for example)

As a start I would go with an API that simply allows adding/removing *rule*->*association* mappings only because it's simpler. We can always extend it later if it is not enough.

What I have in mind is similar to [jsonValidation](https://code.visualstudio.com/api/references/contribution-points#contributes.jsonValidation) contributions for extensions, which I think would be also useful for some extensions. I don't know anything about its inner workings yet though.

**Comment by itowlson** [comment]
The `jsonValidation` level of sophistication certainly suits my needs, and I'm all for simplicity!  An API that would allow me to add a rule-association pair as you describe would be great - thanks!

**Comment by tamasfe** [comment]
I finally got to a new release that should include this as well ([docs](https://taplo.tamasfe.dev/configuration/developing-schemas.html#visual-studio-code-extensions)).

**Comment by itowlson** [comment]
Sweet!  Thanks!
