### ISSUE TITLE
Don't highlight arrays and objects differently

### ISSUE THREAD

**Issue by Aloso** [tamasfe/taplo#25]
This is how my `[dependencies]` section looks like:

![Too many colors](https://user-images.githubusercontent.com/15658558/86181593-a0453000-bb2e-11ea-9dd5-5719cf84a3bf.png)

I don't think that the different colors are useful, I find them distracting. It would be better to use the same color for all keys. If someone wants different colors, they can customize them using the semantic token types.

**Comment by tamasfe** [comment]
I believe this is highly subjective.

The original idea for different colors came from this:

![image](https://user-images.githubusercontent.com/25967296/86184298-2f087b80-bb34-11ea-9493-d1789c195a40.png)

It'd be harder to immediately spot what is an array and what is a table without colors.

The long-term plan is to have proper TextMate grammars where a key is just a key, and then additional semantic colors could be enabled on top of that.

But right now the only colors are provided from the LSP via semantic tokens. It is kind of a hack, but to resolve it someone has to write the actual grammars, and I don't see myself doing it in the near future.

**Comment by Aloso** [comment]
I've written TextMate grammars before, maybe I can help.

**Comment by tamasfe** [comment]
Thanks, I've just asked whether we could use the grammar of [this extension](https://github.com/GalAster/vscode-toml) that was updated for 1.0.0, and the maintainer was very helpful. So hopefully no one needs to type even a single character of regex as they've done it all already.

I don't have a lot of time this week, so you could port it if you want, otherwise I'll get to it this weekend I think.

**Comment by tamasfe** [comment]
This should be resolved in `0.7.0`, by default all keys are the same color and the rest can be colored with custom scopes as suggested. More defails about it is in the updated readme.
