### ISSUE TITLE
Disable `alignEntries` by default

### ISSUE THREAD

**Issue by Aloso** [tamasfe/taplo#29]
I believe that the `evenBetterToml.formatter.alignEntries` setting should be disabled by default. The reason:

Everyone uses version control systems (e.g. git) these days. Most people don't align keys/values in their `Cargo.toml`. This means that contributors have to disable the setting anyway, so their PRs don't reformat the entire `Cargo.toml` file.

On the other hand, if you are the maintainer of a crate and decide that keys/values should be aligned, contributors either have to use "Even Better TOML", or they have to _manually_ align it. Furthermore, if they use `cargo add`, they have to reformat the file afterwards to make sure that the added value is properly aligned.

There is another problem: If you add `very_long_dependency_name = "*"`, all keys must be moved to the right. Even though it modifies only whitespace, the risk of merge conflicts is increased.

That's why I think that aligning entries should be discouraged by making the setting opt-in.

-----

Note that `rustfmt` has a similar setting, `struct_field_align_threshold`, which is set to 0 by default, so struct fields are not aligned by default in Rust.

**Comment by tamasfe** [comment]
Thank you, it's not the first time this was suggested, and the conclusion was that _it comes to personal preference_. However you raise very valid points.

Originally I wanted to create something like the neat struct alignment that Go has by default. However it can only get away with it because gofmt is a standard tool that everyone uses, while Taplo is only available in a specific IDE extension at the moment. I also suppose that the majority of the users will have a Rust background who expect the unaligned behaviour.

I believe `reorderKeys` has similar drawbacks, I was considering disabling that as well, do you have any feedback on that?

**Comment by Aloso** [comment]
> I believe `reorderKeys` has similar drawbacks, I was considering disabling that as well, do you have any feedback on that?

Yes, some of my concerns also apply to `reorderKeys`. It might be best to disable it by default as well.
