### ISSUE TITLE
Even Better TOML default configuration

### ISSUE THREAD

**Issue by smoelius** [tamasfe/taplo#509]
Where do I find Even Better TOML's default configuration?

From what I can tell, it is different from `taplo-cli`'s dafult configuration, which appears to be the one described here: https://taplo.tamasfe.dev/configuration/formatter-options.html

Here is my reason for thinking this. The following file was formatted with Even Better TOML: https://github.com/trailofbits/test-fuzz/blob/44a6c11b0610d4b6c7fdd2c9f55137a0cd23e4ea/test-fuzz/Cargo.toml

But if you format it with `taplo-cli`, the indentation of lines 38 and 39 changes to 2 spaces.

**Comment by ia0** [comment]
Thanks for the question!

Given you talk about Even Better TOML I'm assuming you're using VS Code as your editor. I'm not familiar with it, but it probably has some general settings for LSP client requests, in particular for `textDocument/formatting`, in particular for its [options](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#formattingOptions), and in particular the value of `tabSize` which is probably 4 by default. That's the default in Emacs for TOML files (and that's what is used by eglot to fill that option in the LSP client request). There's probably a way to change this settings somewhere in VS Code and it's probably called "Tab Size".

**Comment by smoelius** [comment]
Thanks very much for your reply, @ia0.

> I'm assuming you're using VS Code as your editor.

That's correct.

> I'm not familiar with it, but it probably has some general settings for LSP client requests...

Please forgive my naiveté, but it sounds like your saying the VS Code extension should use the same default configuration as `taplo-cli`, but that some of those settings may be overridden by the LSP infrastructure?

If that's correct, could you please point me to the code where that would generally occur? I'm presuming that by looking at that code, it should be possible to enumerate (or at least get a sense for) which settings could be overridden(?).

**Comment by ia0** [comment]
> Please forgive my naiveté, but it sounds like your saying the VS Code extension should use the same default configuration as taplo-cli, but that some of those settings may be overridden by the LSP infrastructure?

No, there's no overriding. Let's decompose what happens when you want to format from VS Code:
- VS Code will build some formatting options with at least 2 fields: tabSize (Size of a tab in spaces) and insertSpaces (Prefer spaces over tabs). This is where you get the value 4 for tabSize.
- VS Code will build a formatting request with those options and send it to taplo.
- Taplo will read the request and respond with how to format the document.

When using taplo-cli, there is no formatting options, so taplo-cli has its own internal values, which don't need to be the same as LSP clients like VS Code, and in this case (same with Emacs) they disagree. Taplo uses 2 spaces by default (configurable in the `taplo.toml` file).

There's sadly no way to have a single configuration for both because of how LSP is designed (the 2 fields above are required so VS Code has to take a decision). If your editor is configurable like Emacs, you could in theory read the `taplo.toml` yourself and update tabSize but that's crazy. The simplest option (and that's what I do) is to tell VS Code (Emacs in my case) that for TOML files (or all files if you want) the tab size is 2 and not 4. Alternatively, you can tell Taplo to use 4.

**Comment by smoelius** [comment]
Thanks for the detailed explanation!
