### ISSUE TITLE
Question: standalone LSP

### ISSUE THREAD

**Issue by kkiyama117** [tamasfe/taplo#52]
I'm planning to create standalne lsp with `taplo`, `taplo-ide` and [lsp-server crate from rust-analyzer](https://github.com/rust-analyzer/lsp-server).
But If taplo will soon include standalone lsp feature or @tamasfe will create new crate, I think it's better to contribute to it instead of mine. Please tell me if you have loadmap about standalone lsp.

relation?: #39 #33

**Comment by tamasfe** [comment]
Sounds great, I'd eventually like to allow the usage of Taplo in other IDE-s.

What you're about to do is almost done. (well, after a thorough refactoring)

Currently I use [this](https://github.com/tamasfe/taplo/tree/master/lsp-async-stub), which pretty much does the same as rust-analyzer's lsp-server but works asynchronously to support wasm.

In order to make it standalone, the wasm-specific parts have to be made so that they're conditionally compiled (probably collected into a separate module), and wrap everything in a tokio runtime that calls [this](https://github.com/tamasfe/taplo/blob/master/taplo-ide/src/lib.rs#L280) on an LSP message.

Then implement an alternative `ResponseWriter` that outputs responses to stdout or wherever needed so that the server can respond, it's currently [here](https://github.com/tamasfe/taplo/blob/master/taplo-ide/src/lib.rs#).

It's probably not a small task especially because the `taplo-ide` code is a bit all over the place right now, but definitely smaller than rewriting it for lsp-server.

Either way, I'm happy to help wherever needed.

**Comment by kkiyama117** [comment]
Thank you so much. I'll try it from now on and may create pull request if I've done.
