### ISSUE TITLE
Incorrect error in wrangler.toml

### ISSUE THREAD

**Issue by ethan-tqa** [tamasfe/taplo#589]
Cloudflare recently add new capability to configure Pages in the `wrangler.toml` file, one of the new properties is `pages_build_output_dir`. However the extension is reporting it as error. Please refer to Cloudflare's [doc](https://developers.cloudflare.com/pages/functions/wrangler-configuration/#migrate-from-dashboard-configuration)

**Comment by panekj** [comment]
Errors are based on the available schemas which are provided by [SchemaStore](https://github.com/SchemaStore/schemastore). [Since Cloudflare maintains their own schema, they have to update it.](https://github.com/SchemaStore/schemastore/blob/c20b9a01ec850d7bf19559bd7e20d565b74f3832/src/api/json/catalog.json#L4611-L4616)

**Comment by magicalpuffin** [comment]
For those who find this issue, a temporary workaround is to disable schema validation with: `"evenBetterToml.schema.enabled": false`
Not sure if there is a way to disable schema validation for specific files.
