### ISSUE TITLE
Taplo using almost 20gb of RAM on Zed Editor.

### ISSUE THREAD

**Issue by cleissonalves** [tamasfe/taplo#693]
![Screenshot from 2024-10-31 19-54-10](https://github.com/user-attachments/assets/9e42040f-4eb8-46b8-8162-10d4889f2a9c)

Is it correct to create this issue here instead of Zed repo?

I only have rust-analyzer, Catppuccin Theme and TOML extensions installed.

This possible memory leak happens when installing and uninstalling many themes while rust code and TOML files are opened on the editor.

**Comment by cleissonalves** [comment]
I also use Even Better TOML in vscode. I haven´t experienced any memory leaks there.

**Comment by panekj** [comment]
> Is it correct to create this issue here instead of Zed repo?

I would say no, because I've not seen such issue in any other editors so it could be something that Zed is doing which makes Taplo leak

Zed issue is https://github.com/zed-industries/zed/issues/13190

I don't mind leaving the issue open here but I have no way to reproduce the problem since it happens exclusively on macOS (don't have mac) except for that one Linux report, but still, I can't reproduce it even on Linux.

**Comment by cleissonalves** [comment]
Makes sense. I'm going to close the issue here and follow the issue on Zed. Thanks.
